M48
; DRILL file {KiCad 9.0.1} date 2025-04-23T01:08:38+0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-23T01:08:38+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X147.53Y-90.71
T2
X97.33Y-105.0
X98.6Y-56.74
X149.4Y-71.98
X149.4Y-99.92
M30
