M48
; DRILL file {KiCad 9.0.1} date 2025-04-30T11:52:48+0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-30T11:52:48+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X181.814Y-114.389
T2
X131.614Y-128.679
X132.884Y-80.419
X183.684Y-95.659
X183.684Y-123.599
M30
